//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NoteAppMVC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Note
    {
        public int id { get; set; }
        [DisplayName("Email")]
        [Required(ErrorMessage = "Email is required.")]
        [EmailAddress(ErrorMessage = "Invalid email.")]
        public string email { get; set; }
        [DisplayName("Title")]
        [Required(ErrorMessage = "Title is required.")]
        public string title { get; set; }
        [DisplayName("Content")]
        [Required(ErrorMessage = "Content is required.")]
        [DataType(DataType.MultilineText)]
        public string content { get; set; }
        public string image { get; set; }
        public bool shared { get; set; }
    }
}
